config/routes.rb
Newblog::Application.routes.draw do
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'  
  get 'logout', to: 'sessions#new', as: 'logout'  
  
  resources :users
  resources :sessions 
  root :to => 'posts#index'
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :name, :title, :content
  
  has_many :comments
  has_attached_file :photo,
                :styles => { :medium => "250x250>",
                             :thumb => "100x100>" },
:url => "/posts/:attachment/:id/:style/:basename.:extension",  
:path => ":rails_root/public/posts/:attachment/:id/:style/:basename.:extension"                             

validates_attachment_presence :photo  
validates_attachment_size :photo, :less_than => 1.megabytes  
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']  

                           
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
  protect_from_forgery  
    
  private  
  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end  
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, only: [:new, :edit, :update]
  
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 4)
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end
 
  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def new  
  end  
    
  def create  
    user = User.find_by_email(params[:email])  
    if user  && user.authenticate(params[:password]) 
      session[:user_id] = user.id  
      redirect_to root_url, :notice => "Logged in!"  
    else  
      flash.now.alert = "Invalid email or password"  
      render "new"  
    end  
  end  
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
      def new  
        @user = User.new  
      end  
        
      def create  
        @user = User.new(params[:user])  
        if @user.save
          sessions[:user_id] = @user.id
          redirect_to root_url, :notice => "Signed up!"  
        else  
          render "new"  
        end  
      end  
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newblog</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="/">Blog4U</a>
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li><%= link_to "Home", posts_path %></li>
	          <li><%= link_to "About", '../about' %></li>
	          <li><%= link_to "Contact", '../contact' %></li>
			  <% if current_user %>
			  <li><%= link_to 'New Post', new_post_path %></li>					
			  <li><a heref="#">Logged in as <%= current_user.email %></a></li>
			  <li><%= link_to "Log out", session_path("current"), method: "delete" %></li>
					<% else %>
	          <li><%= link_to "Log In", login_path %></li><% end %>
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>
	
	<div class="container">
	  <div class="row">
	    <div class="span9">
			<% flash.each do |name, msg| %>
			<div class="alert alert-success">
			<a class="close" data-dismiss="alert">×</a>
				<%= msg %>
			</div>
			<% end %>
	        <%= yield %></div>
	    <div class="span3">
	      <h2>About Us</h2>
	      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
	    </div>
	  </div>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Post</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :postdate, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_select :postdate, :class => 'date_select' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class => 'text_area' %>
      </div>
    </div>
    <div class="controls">
      <%= f.file_field :photo, :class => 'text_field' %>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', posts_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/posts/edit.html.erb
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
 <% @posts.each do |post| %>
     <h1><%= post.title %></h1>
        <p>Posted by <%= post.name %> <em><%= post.postdate.strftime('%b %d, %Y') %></em></p>
		<p><%= raw truncate post.content, :length => 300 %></p>
		<p><%= link_to 'Read the article', post_path(post), :class => 'btn' %></p>
    <% end %>
<%= will_paginate @posts, :class => 'apple_pagination' %> 

app/views/posts/new.html.erb
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Posted by <%= @post.name %> <em><%= @post.postdate.strftime('%b %d, %Y') %></em></p>

<p>
  <%= image_tag @post.photo.url(:medium), :class => 'image' %>
  <%= raw @post.content %>
</p>
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
<div class="alert alert-info" style="width:400px">
	<div style="float:right">
	<% if current_user %>
	<%= link_to 'Delete comment', [comment.post, comment], :confirm => 'Are you sure?', :method => :delete, :class => 'btn-mini btn-danger' %>
			<% else %>
	  <% end %>
	</div>
<p><strong>Name:</strong> <%= comment.name %></p>
<em><%= comment.body %></em>
</div>
<% end %>
<h3>Add a comment:</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :Comment %>
	<%= f.text_area :body, :size => '50' %>
</div>
<div class="actions">
	<%= f.submit %>
</div>	
<% end %>
<div class="form-actions">
  <%= link_to 'Back', posts_path, :class => 'btn'  %>
<% if current_user %>
  <%= link_to 'Edit', edit_post_path(@post), :class => 'btn' %>
		<% else %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>  
  
<%= form_for @user do |f| %>  
  <% if @user.errors.any? %>  
    <div class="error_messages">  
      <h2>Form is invalid</h2>  
      <ul>  
        <% @user.errors.full_messages.each do |message| %>  
          <li><%= message %></li>  
        <% end %>  
      </ul>  
    </div>  
  <% end %>  
  <p>  
    <%= f.label :email %>
    <%= f.text_field :email %>  
  </p>  
  <p>  
    <%= f.label :password %>  
    <%= f.password_field :password %>  
  </p>  
  <p>  
    <%= f.label :password_confirmation %>  
    <%= f.password_field :password_confirmation %>  
  </p>  
  <p class="button"><%= f.submit %></p>  
<% end %>